### ISSUE TITLE
Bugs: Page goes up after reloading  

### ISSUE THREAD

**Issue by Subham-Maity** [Subham-Maity/RandomSentenceGenerator#1]
**After reloading the main page up fix this issue**

**Comment by immayurpanchal** [comment]
Hey @Subham-Maity . I can help you. Please assign it to me.

**Comment by Subham-Maity** [comment]
@immayurpanchal  Sure

**Comment by immayurpanchal** [comment]
@Subham-Maity , Issue is fixed and raised the PR. Please Review and let me know if anything else I can help you with.
